//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSOncologyCanvas {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class API : global::System.Configuration.ApplicationSettingsBase {
        
        private static API defaultInstance = ((API)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new API())));
        
        public static API Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.gocanvas.com/apiv2/reference_datas?username=[USERNAME]&password=[PASS" +
            "WORD]")]
        public string REFERENCE_DATA_URL {
            get {
                return ((string)(this["REFERENCE_DATA_URL"]));
            }
            set {
                this["REFERENCE_DATA_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USERNAME {
            get {
                return ((string)(this["USERNAME"]));
            }
            set {
                this["USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PASSWORD {
            get {
                return ((string)(this["PASSWORD"]));
            }
            set {
                this["PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Append")]
        public string ACTION {
            get {
                return ((string)(this["ACTION"]));
            }
            set {
                this["ACTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mosaiq_dataset_01302014")]
        public string NAME {
            get {
                return ((string)(this["NAME"]));
            }
            set {
                this["NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Canvas.xml")]
        public string XML_FILE_NAME {
            get {
                return ((string)(this["XML_FILE_NAME"]));
            }
            set {
                this["XML_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ServerResponse.xml")]
        public string XML_RESPONSE {
            get {
                return ((string)(this["XML_RESPONSE"]));
            }
            set {
                this["XML_RESPONSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.gocanvas.com/apiv2/submissions.xml?username=[USERNAME]&password=[PASS" +
            "WORD]&form_name=[FORM_NAME]")]
        public string SUBMISSION_DATA_URL {
            get {
                return ((string)(this["SUBMISSION_DATA_URL"]));
            }
            set {
                this["SUBMISSION_DATA_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.gocanvas.com/apiv2/images.xml?image_id=[IMAGE_ID]username=[USERNAME]&" +
            "password=[PASSWORD]")]
        public string IMAGE_GET_URL {
            get {
                return ((string)(this["IMAGE_GET_URL"]));
            }
            set {
                this["IMAGE_GET_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oncology")]
        public string USERGROUP {
            get {
                return ((string)(this["USERGROUP"]));
            }
            set {
                this["USERGROUP"] = value;
            }
        }
    }
}
