//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSOncologyCanvas {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DAL : global::System.Configuration.ApplicationSettingsBase {
        
        private static DAL defaultInstance = ((DAL)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DAL())));
        
        public static DAL Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=[SERVER];Initial Catalog=[DATABASE];User Id=[USERNAME];Password=[PASS" +
            "WORD]")]
        public string CONNECTION_STRING {
            get {
                return ((string)(this["CONNECTION_STRING"]));
            }
            set {
                this["CONNECTION_STRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MOSAIQCLSQL")]
        public string ONCOLOGY_SERVER {
            get {
                return ((string)(this["ONCOLOGY_SERVER"]));
            }
            set {
                this["ONCOLOGY_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mosaiq")]
        public string ONCOLOGY_CATALOG {
            get {
                return ((string)(this["ONCOLOGY_CATALOG"]));
            }
            set {
                this["ONCOLOGY_CATALOG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReadingRadPooledUser2")]
        public string ONCOLOGY_USER {
            get {
                return ((string)(this["ONCOLOGY_USER"]));
            }
            set {
                this["ONCOLOGY_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReadingRadPooledUser2")]
        public string ONCOLOGY_PWD {
            get {
                return ((string)(this["ONCOLOGY_PWD"]));
            }
            set {
                this["ONCOLOGY_PWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MOSAIQ_LAST_PT_INDEX_STORE.txt")]
        public string INDEX_STORE_FILE_NAME {
            get {
                return ((string)(this["INDEX_STORE_FILE_NAME"]));
            }
            set {
                this["INDEX_STORE_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_WSOncologyCanvas_GetAllPatients]")]
        public string GET_ALL_PATIENTS {
            get {
                return ((string)(this["GET_ALL_PATIENTS"]));
            }
            set {
                this["GET_ALL_PATIENTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_WSOncologyCanvas_GetLastPT]")]
        public string GET_LAST_PT {
            get {
                return ((string)(this["GET_LAST_PT"]));
            }
            set {
                this["GET_LAST_PT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHCAPPPRODDB;Initial Catalog=SHIELDS_ERROR_LOGGER;User Id=ReadingRadP" +
            "ooledUser;Password=ReadingRadPooledUser")]
        public string CONNECTION_STRING_ERROR_LOGGER {
            get {
                return ((string)(this["CONNECTION_STRING_ERROR_LOGGER"]));
            }
            set {
                this["CONNECTION_STRING_ERROR_LOGGER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebStatusLog.txt")]
        public string LOCAL_WEB_LOG_FILE_NAME {
            get {
                return ((string)(this["LOCAL_WEB_LOG_FILE_NAME"]));
            }
            set {
                this["LOCAL_WEB_LOG_FILE_NAME"] = value;
            }
        }
    }
}
